config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :bathrooms, only: [:index, :show, :destroy]
  end

  resources :bathrooms do
    resources :reviews, only: [:index, :new, :create, :destroy]
  end

  resources :reviews do
    resources :votes do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
  end
end

app/models/bathroom.rb
class Bathroom < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  validates :user, presence: true
  validates :location_name, presence: true
  validates :street_address, presence: true, uniqueness: true
  validates :city, presence: true
  validates :zip_code, length: { is: 5 }
  validates :zip_code, numericality: { only_integer: true }
  validates :description, presence: true

  def self.search(query)
    where("zip_code = ?", "#{query}")
  end

  def avg_rating
    all_ratings = []
    if reviews.empty?
      return 0.0
    else
      reviews.each do |r|
        all_ratings << r.rating.to_f
      end
      (all_ratings.sum / all_ratings.length).round(1)
    end
  end

  paginates_per 5
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :bathroom
  has_many :votes

  validates :body, presence: true
  validates :user, presence: true
  validates :bathroom, presence: true
  validates :rating, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  paginates_per 2
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bathrooms
  has_many :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :profile_photo, ProfilePhotoUploader

  def admin?
    role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  validates :review, presence: true, uniqueness: { scope: :user }
  validates :vote, inclusion: { in: -1..1 }
end

app/controllers/admin/bathrooms_controller.rb
class Admin::BathroomsController < ApplicationController
  before_filter :authorize_admin!
  def index
    if params[:search]
      @bathrooms = Bathroom.search(params[:search]).order(
        "created_at DESC"
      ).page(params[:page])
      @count = Bathroom.search(params[:search]).count
      flash[:notice] = "#{@count} bathroom(s) found in this area."
    else
      @bathrooms = Bathroom.all.order('created_at DESC').page(params[:page])
    end
  end

  def show
    @bathroom = Bathroom.find(params[:id])
    @reviews = @bathroom.reviews.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize_admin!
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = "User Deleted"
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authorize_admin!
    if current_user.nil? || !current_user.admin?
      flash[:notice] = "You are not authorized to view this resource."
      redirect_to root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :profile_photo
  end
end

app/controllers/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: "\"Application Name\" <notifications@example.com>"
end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    if params[:search]
      @bathrooms = Bathroom.search(params[:search]).order(
        "created_at DESC"
      ).page(params[:page])
      @count = Bathroom.search(params[:search]).count
      flash[:notice] = "#{@count} bathroom(s) found in this area."
    else
      @bathrooms = Bathroom.all.order('created_at DESC').page(params[:page])
    end
  end

  def show
    @bathroom = Bathroom.find(params[:id])
    @reviews = @bathroom.reviews.order(created_at: :desc).page(params[:page])
    @review = Review.new
    @vote_total = Vote.group(:review_id).sum(:vote)
  end

  def new
    @bathroom = Bathroom.new
  end

  def create
    @bathroom = Bathroom.new(bathroom_params)
    @bathroom.user = current_user

    if @bathroom.save
      flash[:notice] = "Bathroom Created!"
      redirect_to bathrooms_path
    else
      flash.now[:alert] = @bathroom.errors.full_messages.join(":( ")
      render :new
    end
  end

  def edit
    @bathroom = Bathroom.find(params[:id])
  end

  def update
    @bathroom = Bathroom.find(params[:id])

    if @bathroom.update(bathroom_params)
      flash[:notice] = 'Bathroom Edited'
      redirect_to bathroom_path(@bathroom)
    else
      flash.now[:alert] = @bathroom.errors.full_messages.join(":( ")
      render :edit
    end
  end

  def destroy
    @bathroom = Bathroom.find(params[:id]).destroy
    flash[:notice] = "Bathroom Deleted"
    redirect_to bathrooms_path
  end

  protected

  def bathroom_params
    params.require(:bathroom).permit(:location_name, :street_address,
      :zip_code, :description, :city, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @bathroom = Bathroom.find(params[:bathroom_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @bathroom = Bathroom.find(params[:bathroom_id])
    @review.bathroom = @bathroom
    @review.user = current_user
    @reviews = @bathroom.reviews.order(created_at: :desc).page(params[:page])
    @vote_total = Vote.group(:review_id).sum(:vote)

    if @review.save
      # ReviewNotifier.new_review(@review).deliver_later
      flash[:notice] = "Review saved"
      redirect_to bathroom_path(params[:bathroom_id])
    else
      flash.now[:alert] = @review.errors.full_messages.join(". ")
      render "bathrooms/show"
    end
  end

  def destroy
    @bathroom = Bathroom.find(params[:bathroom_id])
    @deletereview = Review.find(params[:id]).destroy
    flash[:notice] = "Review Deleted"
    redirect_to bathroom_path(@bathroom)
  end

  protected

  def review_params
    params.require(:review).permit(:body, :rating, :bathroom_id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :pre_vote

  def upvote
    if @value.vote == 1
      @value.vote -= 1
    else
      @value.vote = 1
    end
    respond_to do |format|
      @value.save
      @vote_total = Vote.group(:review_id).sum(:vote)
      format.json { render json: @vote_total[@review.id] }
    end
  end

  def downvote
    if @value.vote == -1
      @value.vote += 1
    else
      @value.vote = -1
    end
    respond_to do |format|
      @value.save
      @vote_total = Vote.group(:review_id).sum(:vote)
      format.json { render json: @vote_total[@review.id] }
    end
  end

  protected

  def pre_vote
    @review = Review.find(params[:review_id])
    @value = Vote.find_or_initialize_by(review: @review, user: current_user)
  end
end

app/views/admin/bathrooms/index.html.erb
<div>
  <%= form_tag(bathrooms_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Bathrooms by Zip Code" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
</div>

<h1>
  List of Bathrooms
</h1>

<% @bathrooms.each do |bathroom| %>
  <li>
    <%= link_to bathroom.location_name, bathroom_path(bathroom) %>
    <br>
    <%= bathroom.street_address %>
    <%= button_to "Delete Bathroom", bathroom_path(bathroom), method: :delete %>
  </li>
<%end%>

<%= link_to "Create New Bathroom", new_bathroom_path %>
<%= paginate @bathrooms %>

app/views/admin/bathrooms/show.html.erb
<h1>
  Bathroom at: <%= @bathroom.location_name %>
</h1>

<table>
  <tr>
    <th>Rating</th>
    <th>Street Address</th>
    <th>Zip Code</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @bathroom.avg_rating %></td>
    <td><%= @bathroom.street_address %></td>
    <td><%= @bathroom.zip_code %></td>
    <td><%= @bathroom.description %></td>
  </tr>
</table>

<%= link_to "Back to All Bathrooms", bathrooms_path %>

<%= button_to "Delete this Bathroom", bathroom_path(@bathroom), method: :delete %>

<h2>Reviews</h2>

<div>
  <% @reviews.each do |review| %>

    <div>
      Review: <%= review.body %>
      Bathroom Rating: <%= review.rating %>
      Time of Review: <%= review.created_at %>

      <%= button_to "Delete Review", bathroom_review_path(@bathroom, review.id), method: :delete %>
    </div>
  <% end %>
</div>
<%= paginate @reviews %>

app/views/admin/users/index.html.erb
<%= @users.each do |user| %>
  <p>
    <%= user.email %>
    <%= button_to "Delete this User", admin_user_path(user), method: :delete %>  
  </p>
<% end %>

app/views/bathrooms/edit.html.erb
<div class="row">
  <div class="small-6 small-offset-3 columns">
    <h1 class="header">Edit Bathroom</h1>
    <%= form_for @bathroom do |f| %>

      <%= f.label :location_name %>
      <%= f.text_field :location_name %>

      <%= f.label :street_address %>
      <%= f.text_field :street_address %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Edit Bathroom" %>

    <% end %>
  </div>
</div>

app/views/bathrooms/index.html.erb
<div class="searchbra row">
  <div class="searchbox small-4">
      <%= form_tag(bathrooms_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Bathrooms by Zip Code" %>
        <%= submit_tag "Search", :name => nil %>
      <% end %>
  </div>
</div>

<h1 class="title small-4 small-offset-4">
List of Bathrooms
</h1>

<div class="small-4 small-offset-4">
  <h5><%= link_to "Create New Bathroom", new_bathroom_path %></h5>
</div>

<% @bathrooms.each do |bathroom| %>
  <table class="bathroom-list small-4 small-offset-4">
    <tr>
      <th>Rating</th>
      <th>Location</th>
      <th>Address</th>
      <th>City</th>
    </tr>
    <tr>
      <td><%= bathroom.avg_rating %></td>
      <td><%= link_to bathroom.location_name, bathroom_path(bathroom) %></td>
      <td><%= bathroom.street_address %></td>
      <td><%= bathroom.city %></td>
    </tr>
  </table>
<%end%>

<%= paginate @bathrooms %>

app/views/bathrooms/new.html.erb
<div class="row">
  <div class="small-6 small-offset-3 columns">
    <h1 class="header">Create a Bathroom</h1>
    <%= form_for @bathroom do |f| %>

      <%= f.label :location_name %>
      <%= f.text_field :location_name %>

      <%= f.label :street_address %>
      <%= f.text_field :street_address %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.submit "Create Bathroom" %>

    <% end %>
  </div>
</div>

app/views/bathrooms/show.html.erb
<div class="row">
  <div class="container clearfix text-center">
    <div id="back-to-list">
      <%= button_to "Back to All Bathrooms", bathrooms_path, class: 'button', method: :get %>
    </div>

    <h1>
      <%= @bathroom.location_name %>
    </h1>

    <p>
      <%= @bathroom.street_address %>, <%= @bathroom.city %> <%= @bathroom.zip_code %>
    </p>

    <table align="center">
      <tr>
        <th>Rating</th>
        <th>Description</th>
      </tr>
      <tr>
        <td><%= @bathroom.avg_rating %></td>
        <td><%= @bathroom.description %></td>
      </tr>
    </table>

    <div align="center">
      <iframe
       width="425"
       height="300"
       frameborder="0" style="border:0"
       src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GOOGLE_KEY"] %>
         &q=<%= @bathroom.street_address %>, <%= @bathroom.zip_code %>
         &attribution_source=Google+Maps+Embed+API
         &attribution_ios_deep_link_id=comgooglemaps://?daddr=<%= @bathroom.street_address %>, <%= @bathroom.zip_code %>">
      </iframe>
    </div>


    <% if @bathroom.user == current_user %>
        <ul class="button-group text-center">
          <li><%= button_to "Delete this Bathroom", bathroom_path(@bathroom), method: :delete, class: 'button' %></li>
          <li><%= button_to "Edit this Bathroom", edit_bathroom_path(@bathroom), class: 'button', method: :get %></li>
        </ul>
    <% end %>
        <h2>Reviews</h2>
  </div>
</div>
<div class="row">
  <div class="enter-review">
    <div class="container">
    <%= form_for [@bathroom, @review] do |f| %>

      <%= f.label :body %>
      <%= f.text_field :body %>

      <%= f.label :rating, "Rating (scale of 1 - 5)" %>
      <%= f.text_field :rating %>

      <%= f.submit "Submit" %>
    <% end %>
    </div>
  </div>

    <% @reviews.each do |review| %>
    <div class="container-total-review">
      <div id="vote-div">
        <%= link_to image_tag("Upvote_Edited_Final.png"), upvote_review_votes_path(review), class: 'upvote' %>
          <div class= 'vote-total'>
            <%= @vote_total[review.id] %>
          </div>
        <%= link_to image_tag("Downvote_Edited_Final.png"), downvote_review_votes_path(review), class: 'downvote' %>
      </div>
      <div class="review-container">
        <p><strong>Review:</strong> <%= review.body %></p>
        <p><strong>Bathroom Rating:</strong> <%= review.rating %></p>
        <p><strong>Time of Review:</strong> <%= review.created_at %></p>
        <% if review.user == current_user %>
          <%= button_to "Delete this Review", bathroom_review_path(@bathroom, review.id), method: :delete, class: "button" %>
        <% end %>
      </div>
  </div>
  <% end %>

  <%= paginate @reviews %>
</div>

app/views/homes/index.html.erb
  <div id="welcome" class="small-4 small-offset-4 columns">
    <h1><%= link_to "Explore Bathrooms", bathrooms_path %></h1>
    <%= form_tag(bathrooms_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Bathrooms by Zip Code" %>
      <%= submit_tag "Search", :name => nil, class: "button" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Writing On The Stall</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <%= link_to image_tag("Toilet-Sign-White.png"), bathrooms_path %>
        <h1><a href="/">Writing On The Stall</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <div class='profile-photo'>
            <div class='user-email'>
              <%= current_user.email %>
            </div>
            <%- if current_user.profile_photo.file == nil -%>
              <li><%= link_to image_tag("default.png"), edit_user_registration_path, id: "edit-profile" %></li>
            <%- else -%>
              <li><%= link_to image_tag(current_user.profile_photo), edit_user_registration_path, id: "edit-profile" %></li>
            <%- end -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
          </div>
      </ul>
    </section>
  </nav>

  <% flash.keys.each do |type| %>
    <% flash[type].split(":( ").each do |f| %>
      <div data-alert class="flash <%= type %> alert-box radius">
          <%= f %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  <% end %>

<div class="page-wrap">
  <%= yield %>
</div>

<footer class="site-footer">
  <div class="large-12 columns">
   <hr/>
   <div class="row">
       <%= image_tag("Facebook-50.png") %>
      <ul class="inline-list right">
        <li><strong id="created">Created By</strong></li><br>
        <li><%= link_to "Brian Stern", "https://github.com/bsterno" %></li>
        <li><%= link_to "Elise Fitzgerald", "https://github.com/EliseFitz15" %></li>
        <li><%= link_to "Ian Noble", "https://github.com/irnoble" %></li>
        <li><%= link_to "Joseph Tessel", "https://github.com/JosephTessel" %></li>
        <li><%= link_to "Kelsey Hale", "https://github.com/KelseyHale"%></li>
      </ul>
      </div>
  </div>
</footer>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/review_notifier/new_review.text.erb
Hello <%= @review.bathroom.user.email %>,

<%= @review.user.email %> has left a new review for your product <%= @review.bathroom.location_name %>.

Peace!